# -*- coding: utf-8 -*-
"""dataloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5PntBtcfoucm-fzaFxfmDT4UhQjrXE9
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pickle
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

import torch
from torch.utils.data import Dataset, DataLoader


# === Global Settings ===
FILE_DIR = "/content/drive/MyDrive/BOAZ_mini2/"
RAW_FILE_NAME = "final_df_3.csv"  # 1차 전처리한 원본 데이터
SAVE_NAME = "ID_Index_mappings.pkl"  # ID-Index 매핑테이블
PREPROCESSED_FILENAME = "final_preprocessed_df.parquet" # 최종 전처리 파일 (train/test 분리 이전)

# === Train / Valid / Test Split Ratios (전역 파라미터) ===
TRAIN_RATIO = 0.8
VALID_RATIO = 0.1
TEST_RATIO  = 0.1

# === DataLoader / Target 관련 전역 파라미터 ===
TARGET_COL = "target"
BATCH_SIZE = 1024
NUM_WORKERS = 4
PIN_MEMORY = True
SHUFFLE_TRAIN = True

"""데이터 시간 순 정렬"""

def sort_by_event_time(df):
    """
    event_time 컬럼을 기준으로 오름차순 정렬하는 함수.
    - event_time이 문자열인 경우 datetime으로 변환 후 정렬
    """

    # datetime 변환 (문자열일 경우 대비)
    if not pd.api.types.is_datetime64_any_dtype(df["event_time"]):
        df["event_time"] = pd.to_datetime(df["event_time"], errors="coerce")

    # 정렬
    df = df.sort_values(by="event_time").reset_index(drop=True)

    return df

"""컬럼 정리"""

def drop_event_time(df):
    # event_time → 이미 hour/day_of_week/is_weekend 로 파생되었으므로 제거
    if 'event_time' in df.columns:
        df = df.drop(columns=['event_time'])
    return df

def validate_and_cleanup_event_columns(df):
    """
    1. event_type → 숫자 코드로 변환 (view=0, cart=1, purchase=2)
    2. 이 숫자가 event_label, target과 모두 동일한지 검증
    3. 동일하면 target만 남기고 event_type, event_label 제거
    """

    # 1) 문자열 → 숫자 매핑
    mapping = {
        "view": 0,
        "cart": 1,
        "purchase": 2
    }

    # 새 컬럼 생성
    df["event_type_code"] = df["event_type"].map(mapping)

    # event_type_code가 제대로 만들어졌는지 체크
    if df["event_type_code"].isnull().any():
        raise ValueError("event_type에 예상치 못한 문자열이 포함되어 있습니다.")

    # 2) event_label, target 과 같은지 확인
    cond_label_match  = (df["event_type_code"] == df["event_label"]).all()
    cond_target_match = (df["event_type_code"] == df["target"]).all()

    print("event_type_code vs event_label 동일? :", cond_label_match)
    print("event_type_code vs target 동일?      :", cond_target_match)

    # 3) 둘 다 모두 일치하는 경우만 컬럼 제거
    if cond_label_match and cond_target_match:
        print("✔ 모든 값이 동일하므로 target만 남기고 event_type, event_label 제거합니다.")
        df = df.drop(columns=["event_type", "event_label", "event_type_code"])
    else:
        print("✘ 세 컬럼이 동일하지 않습니다. 파일을 직접 다시 확인해야 합니다.")
        print("일치하지 않는 예시:")
        mismatched = df[(df["event_type_code"] != df["event_label"]) |
                        (df["event_type_code"] != df["target"])].head()
        print(mismatched)
        # 여기서 drop은 수행하지 않음

    return df

def convert_target_to_softlabel(df):
    """
    target 값을 0/1/2 → 0/0.5/1 로 변환하는 함수.
    - 0(view)      → 0.0
    - 1(cart)      → 0.5
    - 2(purchase)  → 1.0
    """
    mapping = {
        0: 0.0,
        1: 0.5,
        2: 1.0
    }

    # 안전장치: 예상 밖 값이 있으면 에러
    unique_vals = set(df["target"].unique())
    unexpected = unique_vals - set(mapping.keys())
    if unexpected:
        raise ValueError(f"target에 예상치 못한 값이 있습니다: {unexpected}")

    df["target"] = df["target"].map(mapping).astype(float)

    return df

"""object 타입 정제"""

def clean_object_columns(df):
    """
    category_code, brand, user_session 같은 object 타입 문자열을
    일관성 있게 정제하는 함수.

    처리 내용:
    - NaN → 'unknown'
    - 문자열로 변환
    - 앞뒤 공백 제거
    - 소문자로 통일
    """

    object_cols = ["category_code", "brand", "user_session"]

    for col in object_cols:
        df[col] = (
            df[col]
            .fillna("unknown")   # null 대비 (이미 없지만 안전장치)
            .astype(str)         # 문자열로 강제 변환
            .str.strip()         # 앞뒤 공백 제거
            .str.lower()         # 소문자로 통일
        )

    return df

"""수치형 변수"""

def scale_numerical_features(df):

    df = df.copy()

    PRICE_COL = "price"
    OTHER_NUMERIC = ["session_rank", "hour", "day_of_week"]  # is_weekend 제외

    # ------------------------
    # 1) price: log1p + MinMaxScaling
    # ------------------------
    if PRICE_COL in df.columns:
        df["price_log"] = np.log1p(df[PRICE_COL])
        scaler_price = MinMaxScaler()
        df["price_scaled"] = scaler_price.fit_transform(df[["price_log"]])
        df.drop(columns=[PRICE_COL, "price_log"], inplace=True)
        print("✅ price: log1p + MinMaxScaling → price_scaled 생성")

    # ------------------------
    # 2) 나머지 수치형 (session_rank, hour, day_of_week)
    # ------------------------
    cols_to_scale = [col for col in OTHER_NUMERIC if col in df.columns]

    for col in cols_to_scale:
        scaler = MinMaxScaler()
        df[f"{col}_scaled"] = scaler.fit_transform(df[[col]])
        df.drop(columns=[col], inplace=True)

    if cols_to_scale:
        print(f"✅ {cols_to_scale}: MinMaxScaling → *_scaled 생성")

    # ------------------------
    # 3) is_weekend는 그대로 유지 (스케일링 X)
    # ------------------------
    print("ℹ️ is_weekend: 변경 없음 (0/1 그대로 유지)")

    return df

"""범주형 변수 \
-> ID - Index 매핑 테이블 생성( .pkl)
"""

def build_and_apply_mappings(df: pd.DataFrame, drop_original=True):
    """
    6개 카테고리 변수(product_id, category_id, category_code, brand, user_id, user_session)에 대해
    원래값 → 인덱스 매핑 생성 + df에 *_idx 컬럼 생성 + 매핑 파일 저장
    """

    # 저장 경로
    save_path = os.path.join(FILE_DIR, SAVE_NAME)

    # 디렉토리 없으면 생성
    os.makedirs(FILE_DIR, exist_ok=True)

    cat_cols = [
        "product_id",
        "category_id",
        "category_code",
        "brand",
        "user_id",
        "user_session",
    ]

    # unknown을 0번으로 보내고 싶은 컬럼
    unknown_as_zero_cols = {"category_code", "brand"}

    mappings = {}

    for col in cat_cols:
        col_series = df[col].astype(str)
        uniques = pd.unique(col_series)

        col_map = {}
        next_idx = 0

        # 1) unknown을 0번 인덱스로 고정해야 하는 경우
        if col in unknown_as_zero_cols and "unknown" in uniques:
            col_map["unknown"] = 0
            next_idx = 1
            uniques = [u for u in uniques if u != "unknown"]

        # 2) 나머지 값들 인덱스 부여
        for v in uniques:
            col_map[v] = next_idx
            next_idx += 1

        mappings[col] = col_map

        # 3) df에 인덱스 컬럼 추가
        df[col + "_idx"] = col_series.map(col_map).astype("int32")

    # 4) 원본 컬럼 삭제 여부
    if drop_original:
        df = df.drop(columns=cat_cols)

    # 5) 매핑 피클 저장
    with open(save_path, "wb") as f:
        pickle.dump(mappings, f)

    print(f"매핑 파일 저장됨 → {save_path}")
    return df, mappings

"""seq_prod 컬럼 \
-> DeepFM, AutoInt 모델은 리스트를 입력으로 받지 못함 \
-> 컬럼 5개로 분리 \
-> 인덱싱은 product_id로 생성한 테이블 이용해 매칭
"""

def apply_seq_prod_mapping(df, mappings, seq_col="seq_prod", max_len=5):
    """
    seq_prod 컬럼(길이 5짜리 product_id 리스트)을
    seq_prod_1_idx ~ seq_prod_5_idx 로 변환하는 함수.

    규칙:
    - seq_prod[0] = 가장 오래된 과거 행동 → seq_prod_1_idx
    - ...
    - seq_prod[4] = 직전 과거 행동      → seq_prod_5_idx
    - 값이 0인 곳(패딩)은 product_id 매핑에 없으므로 자동으로 0으로 남음.
    """

    prod_map = mappings["product_id"]  # 기존 product_id 매핑 재사용

    def to_list(seq):
        # 문자열로 저장된 경우도 대비
        if isinstance(seq, str):
            try:
                seq = ast.literal_eval(seq)
            except Exception:
                return []
        if isinstance(seq, (list, tuple)):
            return list(seq)
        return []

    seq_series = df[seq_col].apply(to_list)

    for i in range(max_len):
        new_col = f"{seq_col}_{i+1}_idx"   # seq_prod_1_idx ~ seq_prod_5_idx

        df[new_col] = seq_series.apply(
            lambda seq: (
                prod_map.get(str(seq[i]), 0)  # i번째 product_id → 인덱스, 없으면 0
                if len(seq) > i
                else 0                        # 리스트가 더 짧으면 PAD처럼 0
            )
        ).astype("int32")

    # 🔥 여기서 원본 seq_prod 컬럼 삭제
    df = df.drop(columns=[seq_col])

    return df

"""최종 전처리 파일 저장"""

def save_preprocessed_parquet(df, file_dir, filename="final_preprocessed_df.parquet"):
    """
    전처리 완료된 DataFrame을 parquet 형태로 저장하는 함수.
    - df: 전처리 완료된 DataFrame
    - file_dir: 저장할 디렉토리 경로
    - filename: 저장할 파일 이름 (기본값: final_preprocessed_df.parquet)
    """
    # 경로 생성
    os.makedirs(file_dir, exist_ok=True)
    save_path = os.path.join(file_dir, filename)

    # parquet 저장
    df.to_parquet(save_path, index=False)

    print(f"[INFO] Parquet 저장 완료: {save_path}")
    return save_path

"""$\text{Train}/\text{Test}$ 분리"""

def split_exact_tvt_from_preprocessed(
    random_state=42,
):
    """
    전역변수: FILE_DIR, PREPROCESSED_FILENAME, TRAIN_RATIO, VALID_RATIO, TEST_RATIO를 사용해
    parquet 파일을 자동으로 읽고 정확한 비율 split을 수행하는 함수.
    """

    # 비율 합 확인
    assert abs((TRAIN_RATIO + VALID_RATIO + TEST_RATIO) - 1.0) < 1e-6, \
        "TRAIN_RATIO + VALID_RATIO + TEST_RATIO must equal 1."

    # Load parquet
    parquet_path = os.path.join(FILE_DIR, PREPROCESSED_FILENAME)
    print(f"[INFO] Loading preprocessed parquet from: {parquet_path}")
    df = pd.read_parquet(parquet_path)

    n = len(df)

    # === Test: 최신 TEST_RATIO 만큼 뒤쪽 ===
    test_start = int(n * (1 - TEST_RATIO))
    df_test = df.iloc[test_start:].reset_index(drop=True)
    df_early = df.iloc[:test_start].reset_index(drop=True)

    # === 전체 기준 정확한 train/valid 개수 ===
    exact_train_n = int(n * TRAIN_RATIO)
    exact_valid_n = int(n * VALID_RATIO)

    # === df_early에서 train/valid 랜덤 샘플링 ===
    df_train = df_early.sample(n=exact_train_n, random_state=random_state)
    df_valid = df_early.drop(df_train.index).sample(n=exact_valid_n, random_state=random_state)

    # reset index
    df_train = df_train.reset_index(drop=True)
    df_valid = df_valid.reset_index(drop=True)

    print(f"[INFO] TOTAL: {n:,}")
    print(f"[INFO] Train: {len(df_train):,} ({TRAIN_RATIO*100:.1f}%)")
    print(f"[INFO] Valid: {len(df_valid):,} ({VALID_RATIO*100:.1f}%)")
    print(f"[INFO] Test : {len(df_test):,} ({TEST_RATIO*100:.1f}%)")

    return df_train, df_valid, df_test

"""Dataset 정의"""

# ==========================
# PyTorch Dataset 정의
# ==========================
class CTRDataset(Dataset):
    """
    - df: 하나의 split (train/valid/test)
    - feature_cols: TARGET_COL을 제외한 피처 컬럼 리스트
    - target_col : 타겟 컬럼명 (전역 TARGET_COL 기본값)
    """

    def __init__(self, df: pd.DataFrame, feature_cols, target_col: str = TARGET_COL):
        self.df = df
        self.feature_cols = list(feature_cols)
        self.target_col = target_col

        # dtype 체크 (object/string 남아 있으면 경고)
        obj_cols = df[self.feature_cols].select_dtypes(include=["object"]).columns.tolist()
        if len(obj_cols) > 0:
            print(f"[WARN] Object dtype feature columns detected: {obj_cols}")
            print("       모델 넣기 전에 모두 인덱싱/인코딩 되어 있어야 함!")

        # values로 미리 뽑아두기
        self.X = self.df[self.feature_cols].values.astype(np.float32)
        self.y = self.df[self.target_col].values.astype(np.float32)  # soft label 0/0.5/1 기준

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        x = torch.from_numpy(self.X[idx])
        y = torch.tensor(self.y[idx], dtype=torch.float32)
        return x, y

"""DataLoader 생성"""

# ==========================
# DataLoader 생성 함수
# ==========================
def create_dataloaders_from_df(train_df, valid_df, test_df):
    """
    이미 split_exact_tvt_from_preprocessed()로 나눈
    train_df, valid_df, test_df를 받아서

    1) feature_cols = 전체 컬럼 - TARGET_COL
    2) CTRDataset 생성
    3) DataLoader까지 생성
    """

    # 1) feature 컬럼 자동 추출
    all_cols = train_df.columns.tolist()
    assert TARGET_COL in all_cols, f"[ERROR] TARGET_COL '{TARGET_COL}' not in dataframe columns."

    feature_cols = [c for c in all_cols if c != TARGET_COL]

    print(f"[INFO] Feature columns ({len(feature_cols)}): {feature_cols}")
    print(f"[INFO] Target column: {TARGET_COL}")

    # 2) Dataset 생성
    train_dataset = CTRDataset(train_df, feature_cols, TARGET_COL)
    valid_dataset = CTRDataset(valid_df, feature_cols, TARGET_COL)
    test_dataset  = CTRDataset(test_df,  feature_cols, TARGET_COL)

    # 3) DataLoader 생성
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=SHUFFLE_TRAIN,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    valid_loader = DataLoader(
        valid_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        drop_last=False,
    )

    return train_loader, valid_loader, test_loader, feature_cols

"""메인 함수"""

if __name__ == "__main__":
    # 0) CSV 경로 설정 (전역 FILE_DIR, RAW_FILE_NAME 사용)
    file_path = os.path.join(FILE_DIR, RAW_FILE_NAME)
    df = pd.read_csv(file_path)
    df1 = df.copy()

    # 0) event_time 기준으로 정렬 (가장 먼저!)
    df1 = sort_by_event_time(df1)

    # 1) event_time 제거
    df1 = drop_event_time(df1)

    # 2) event_type / event_label / target 검증 & 정리
    df1 = validate_and_cleanup_event_columns(df1)

    # 3) target 0/1/2 → 0/0.5/1 변환
    df1 = convert_target_to_softlabel(df1)

    # 4) object 컬럼 정제
    df1 = clean_object_columns(df1)

    # 5) 수치형 스케일링 (price log변환 + MinMax, 다른 수치형 MinMax, is_weekend(0/1) 제외)
    df1 = scale_numerical_features(df1)

    # 6) 카테고리 변수 6개 인덱싱 + 매핑 피클 저장
    df1, mappings = build_and_apply_mappings(df1, drop_original=True)

    # 7) seq_prod 인덱싱 (가장 과거 → 1, 직전 행동 → 5)
    df1 = apply_seq_prod_mapping(df1, mappings, seq_col="seq_prod", max_len=5)

    # === 8) 최종 전처리 결과 parquet 저장 ===
    save_preprocessed_parquet(df1, FILE_DIR, filename="final_preprocessed_df.parquet")

    # 9) Split 여기서는 80 : 10 : 10 기준 (AutoInt 논문과 동일)
    train_df, valid_df, test_df = split_exact_tvt_from_preprocessed(
        random_state=42
    )
    print("[INFO] Split completed. Ready to build DataLoaders or Models.")

    # 10) DataLoader 생성
    train_loader, valid_loader, test_loader, feature_cols = create_dataloaders_from_df(
        train_df, valid_df, test_df
    )
    print("[INFO] DataLoaders created.")

batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape)
print(batch_y.shape)

"""PKL 검증 스니펫"""

import pickle
import os
import pandas as pd

full_file_path = os.path.join(FILE_DIR, SAVE_NAME)

# 피클 로드
with open(full_file_path, "rb") as f:
    id_maps = pickle.load(f)

print("=== 피클 파일 로드 성공 ===")
print(f"저장된 컬럼: {list(id_maps.keys())}")

print("\n======================================")
print("🔎 1) 앞 20개 매핑 확인")
print("======================================")
for col, mapping in id_maps.items():
    print(f"\n[{col}] 앞 20개:")
    items = list(mapping.items())[:20]
    for k, v in items:
        print(f"  {k} -> {v}")

print("\n======================================")
print("🔎 2) unknown = 0 확인")
print("======================================")
for col in ["category_code", "brand"]:
    if "unknown" in id_maps[col]:
        print(f"{col}: unknown → {id_maps[col]['unknown']}")
    else:
        print(f"{col}: unknown 없음 (정상)")

print("\n======================================")
print("🔎 3) 인덱스 범위 확인")
print("======================================")
for col, mapping in id_maps.items():
    vals = list(mapping.values())
    print(f"{col}: 최소={min(vals)}, 최대={max(vals)}, 개수={len(vals)}")

print("\n======================================")
print("🔎 4) 중복 인덱스 존재 여부")
print("======================================")
for col, mapping in id_maps.items():
    vals = list(mapping.values())
    if len(vals) != len(set(vals)):
        print(f"⚠️ {col}: 인덱스 중복 있음!")
    else:
        print(f"✅ {col}: 인덱스 중복 없음 (정상)")

print("\n======================================")
print("🔎 5) DataFrame 형태로 미리보기 (앞 20개)")
print("======================================")
for col, mapping in id_maps.items():
    print(f"\n[{col}] 매핑 테이블 미리보기 20개:")
    df_map = pd.DataFrame(list(mapping.items()), columns=[col, col + "_idx"])
    display(df_map.head(20))
    print("-" * 60)